version: '3.8'
services:
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: scalaure123
      POSTGRES_DB: dev

  db-test:
    image: postgres:14.4-alpine
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: scalaure123
      POSTGRES_DB: test
